Xa = int(input('Nhập hoành độ x của A: '))
Ya = int(input('Nhập tung độ y của A: '))
Xb = int(input('Nhập hoành độ x của B: '))
Yb = int(input('Nhập tung độ y của B: '))
Xc = int(input('Nhập hoành độ x của C: '))
Yc = int(input('Nhập tung độ y của C: '))
XG = round((Xa+Xb+Xc)/3,2)
YG = round((Ya+Yb+Yc)/3,2)
print(f'Trọng tâm tam giác ABC là: G({XG},{YG})')