ma_sv = input("nhập mã sinh viên:") 
ho_ten= input("nhập họ tên:") 
quê_quán= input("nhập quê quán:") 
nam_sinh=input("nhập năm sinh:") 
diem_TB=float(input("điểm TB:")) 
print("mã sinh viên: ", ma_sv) 
print("họ tên: ", ho_ten) 
print("quê quán: ", quê_quán)
print("năm sinh: ", nam_sinh) 
print("diem_TB: ", diem_TB)