import os
ma=input("ma sv:")
ten=input("ho ten:")
que=input("que quan:")
nam=input("nam sinh:")
diem=input("diem tb:")
os.system("cls")
print("ma sinh vien:",ma)
print("ho ten:",ten)
print("que quan:",que)
print("nam sinh:",nam)
print("diem trung binh:",diem)