mã_sv = input("Nhập mã sinh viên:")
họ_tên= input("Nhập họ tên:")
quê_quán= input("Nhập quê quán:")
năm_sinh=input("Nhập năm sinh:")
diem_TB=float(input("Điểm TB:"))
print("mã sinh viên: ", mã_sv)
print("họ tên: ", họ_tên)
print("quê quán: ", quê_quán)
print("năm sinh: ", năm_sinh)
print("diem_TB: ", diem_TB)