a=int(input('mời nhập tọa độ x: '))
b=int(input("mời nhập tọa độ y: "))
c=int(input("mời nhập tọa độ z: "))
print("tọa độ đối xứng của Oxy là: ","(",a,b,-c,")")
print("tọa độ đối xứng của Oxz là: ","(",a,-b,c,")")
print("tọa độ đối xứng của Oyz là: ","(",-a,b,c,")")