masv=int(input('nhập mã sinh viên của bạn:'))
ten=input('nhập họ tên:')
que=input('nhập quê quán:')
namsinh=int(input('nhập năm sinh:'))
dtb=float(input('nhập điểm trung bình các năm học:'))
print('THÔNG TIN VỪA NHẬP CỦA BẠN LÀ:')
print('mã sinh viên của bạn là:',masv)
print('họ tên:',ten)
print('quê quán:',que)
print('năm sinh:',namsinh)
print('điêm trung bình là:',dtb)
