d=int(input("nhap so ngay: "))
h=int(input("nhap so gio: "))
m=int(input("nhap so phut: "))
s=int(input("nhap so giay: "))
print("{}ngay,{}gio,{}phut,{}giay".format(d,h,m,s),"bang",round(d+(h/24)+(m/1440)+(s/86400),2),"ngay")
print("{}ngay,{}gio,{}phut,{}giay".format(d,h,m,s),"bang",round(d*24+h+(m/60)+(s/3600),2),"gio")
print("{}ngay,{}gio,{}phut,{}giay".format(d,h,m,s),"bang",round(d*1440+(h*60)+(m)+(s/60),2),"phut")
print("{}ngay,{}gio,{}phut,{}giay".format(d,h,m,s),"bang",round(s+(m*24)+(h*1440)+(d*86400),2),"giayy")