xa=float(input('Tọa độ x điểm A: '))
ya=float(input('Tọa độ y điểm A: '))
xb=float(input('Tọa độ x điểm B: '))
yb=float(input('Tọa độ y điểm B: '))
xc=float(input('Tọa độ x điểm C: '))
yc=float(input('Tọa độ y điểm C: '))
xg=round((xa+xb+xc)/3,2)
yg=round((ya+yb+yc)/3,2)
print('Tọa độ trọng tâm G của tam giác ABC là: G(',xg,";",yg,")")