print('Nhập vecto a:')
x1=int(input('Nhập giá trị x1:'))
x2=int(input('Nhập giá trị x2:'))
print('Nhập vecto b:')
y1=int(input('Nhập giá trị y1:'))
y2=int(input('Nhập giá trị y2:'))
print('Tích vô hướng của 2 vecto:',x1*y1+x2*y2)