xa = int(input('Nhập hoành độ x của A: '))
ya = int(input('Nhập tung độ y của A: '))
xb = int(input('Nhập hoành độ x của B: '))
yb = int(input('Nhập tung độ y của B: '))
xc = int(input('Nhập hoành độ x của C: '))
yc = int(input('Nhập tung độ y của C: '))
xG = round((xa+xb+xc)/3,2)
yG = round((ya+yb+yc)/3,2)
print(f'Trọng tâm tam giác ABC là: G({xG},{yG})')