r=int(input("nhap ban kinh: "))
h=int(input("nhap chieu cao: "))
print("dien tich xung quanh cua hinh tru la",round(2*r*3.14*h,2))
print("dien tich toan phan cua hinh tru la",round((2*r*3.14*h)+r*r*3.14,2))
print("the tich cua hinh tru la",round(3.14*r*r*h,2))