print("a là hệ số của x^2")
a=eval(input("Nhập hệ số a "))
print("b là hệ số của x")
b=eval(input("Nhập hệ số b "))
print("c là hệ số tự do")
c=eval(input("Nhập hệ số c "))
x=-b/(2*a)
print("vậy phương trình sau khi nhập hệ số là")
print(a*'x^2',b*'x',c)
print("đỉnh của phương trình đã nhập là ",round(x,2))